### ISSUE TITLE
Pending tasks for gardener integration

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/kupid#14]
**What would you like to be added**:

- [x] General solution for reserving excess capacity (both on common and dedicated nodes). A tentative solution is [here](https://github.com/amshuman-kr/reserve-excess-capacity).
- [x] Genera solution in the landscape deployment to create dedicated worker pools for etcd and to reserve excess capacity.

**Why is this needed**:
To complete the integration with gardener.

**Comment by vlerenc** [comment]
@amshuman-kr Please forgive brevity while grooming the backlog. Issue still relevant or would you like to close it?

Specifically, shall we keep up the excess capacity? I have the feeling that we usually anyways have enough "holes" (space) on the nodes and with two worker pools that just got more likely (fragmentation because of two pools).

As for dedicated worker pools for ETCD and the deployment and integration into landscape-setup, please note that with the landscaper, things will change again. So whether or not we need to do something depends on how far/how long the current solution can carry us until the landscaper will anyways take over and things change again.

**Comment by amshuman-kr** [comment]
@vlerenc [gardener/reserve-excess-capacity](https://github.com/gardener/reserve-excess-capacity) got published yesterday and I am working on integrating with LSS scripts. So, I will close this issue soon (as soon as the LSS changes go in).

**Comment by amshuman-kr** [comment]
Fixed with [gardener/reserve-excess-capacity](https://github.com/gardener/reserve-excess-capacity).
